version: 2
updates:
  # Mantener dependencias de npm actualizadas
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "eduardodevaltamedica"
    assignees:
      - "eduardodevaltamedica"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    ignore:
      # Ignorar dependencias que requieren cambios manuales
      - dependency-name: "@types/*"
      - dependency-name: "typescript"
      - dependency-name: "next"
      - dependency-name: "react"
      - dependency-name: "react-dom"

  # Mantener dependencias de GitHub Actions actualizadas
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "eduardodevaltamedica"
    assignees:
      - "eduardodevaltamedica"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Mantener dependencias de Docker actualizadas
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "eduardodevaltamedica"
    assignees:
      - "eduardodevaltamedica"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # Mantener dependencias de Terraform actualizadas
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "eduardodevaltamedica"
    assignees:
      - "eduardodevaltamedica"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "terraform"
