# GitHub Secrets Configuration
# Copia este archivo a tu configuración de GitHub Secrets

# Turbo Remote Cache
TURBO_TOKEN: "your-turbo-token-here"
TURBO_TEAM: "your-turbo-team-here"

# Code Coverage
CODECOV_TOKEN: "your-codecov-token-here"

# Firebase (Production)
FIREBASE_API_KEY: "your-firebase-api-key"
FIREBASE_AUTH_DOMAIN: "your-firebase-auth-domain"
FIREBASE_PROJECT_ID: "your-firebase-project-id"
FIREBASE_STORAGE_BUCKET: "your-firebase-storage-bucket"
FIREBASE_MESSAGING_SENDER_ID: "your-firebase-messaging-sender-id"
FIREBASE_APP_ID: "your-firebase-app-id"
FIREBASE_SERVICE_ACCOUNT: "base64-encoded-service-account-json"

# Database
DATABASE_URL: "postgresql://user:password@localhost:5432/altamedica"

# Deployment
VERCEL_TOKEN: "your-vercel-token"
VERCEL_ORG_ID: "your-vercel-org-id"
VERCEL_PROJECT_ID: "your-vercel-project-id"

# Monitoring
SENTRY_DSN: "your-sentry-dsn"
SENTRY_AUTH_TOKEN: "your-sentry-auth-token"

# Medical APIs (Optional)
OPENAI_API_KEY: "your-openai-api-key"
GOOGLE_MAPS_API_KEY: "your-google-maps-api-key"