version: '3.8'

services:
  altamedica-api:
    build:
      context: .
      dockerfile: Dockerfile.enterprise
    container_name: altamedica-api-server
    ports:
      - "3001:3001"
      - "8080:8080"
      - "10000-10100:10000-10100/udp"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://altamedica:secure_password@postgres:5432/altamedica_db
      - REDIS_URL=redis://redis:6379
      - FIREBASE_PROJECT_ID=altamedica-prod
      - JWT_SECRET=your_jwt_secret_here
      - WEBRTC_LISTEN_IP=0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - altamedica-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    container_name: altamedica-postgres
    environment:
      POSTGRES_DB: altamedica_db
      POSTGRES_USER: altamedica
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - altamedica-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U altamedica -d altamedica_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: altamedica-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - altamedica-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: altamedica-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: altamedica
      MONGO_INITDB_ROOT_PASSWORD: secure_password
      MONGO_INITDB_DATABASE: altamedica_ai
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - altamedica-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: altamedica-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - altamedica-api
    networks:
      - altamedica-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: altamedica-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - altamedica-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: altamedica-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: altamedica_admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - altamedica-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  mongodb_data:
  prometheus_data:
  grafana_data:

networks:
  altamedica-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
