# 📊 PROMETHEUS CONFIGURATION - ALTAMEDICA MEDICAL PLATFORM
# Monitoreo y métricas para aplicaciones médicas empresariales
# Optimizado para HIPAA compliance y alta disponibilidad

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'altamedica-medical'
    environment: 'production'

# ==========================================
# SCRAPE CONFIGURATIONS - MEDICAL SERVICES
# ==========================================

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 10s
    metrics_path: /metrics

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
    scrape_timeout: 5s

  # API Server - Core medical backend
  - job_name: 'api-server'
    static_configs:
      - targets: ['api-server:3000']
    metrics_path: /api/v1/metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # Signaling Server - WebRTC
  - job_name: 'signaling-server'
    static_configs:
      - targets: ['signaling-server:8888']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL - Database metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis - Cache metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx - Reverse proxy metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /nginx_status
    scrape_interval: 15s
    scrape_timeout: 5s