apiVersion: v1
kind: ConfigMap
metadata:
  name: firebase-config
  namespace: altamedica
data:
  config: |
    {
      "apiKey": "AIzaSyB_example",
      "authDomain": "altamedica.firebaseapp.com",
      "projectId": "altamedica",
      "storageBucket": "altamedica.appspot.com",
      "messagingSenderId": "123456789",
      "appId": "1:123456789:web:abcdef123456"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-config
  namespace: altamedica
data:
  url: "https://xyzcompany.supabase.co"
  anon-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.example"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-config
  namespace: altamedica
data:
  cors.json: |
    {
      "origin": [
        "https://altamedica.com",
        "https://www.altamedica.com",
        "https://doctors.altamedica.com",
        "https://patients.altamedica.com",
        "https://admin.altamedica.com"
      ],
      "credentials": true
    }
  rate-limit.json: |
    {
      "windowMs": 900000,
      "max": 100,
      "standardHeaders": true,
      "legacyHeaders": false
    }
  hipaa.json: |
    {
      "auditLogging": true,
      "encryptionRequired": true,
      "sessionTimeout": 900000,
      "maxLoginAttempts": 5,
      "passwordPolicy": {
        "minLength": 12,
        "requireUppercase": true,
        "requireLowercase": true,
        "requireNumbers": true,
        "requireSpecial": true
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: recaptcha-config
  namespace: altamedica
data:
  site-key: "6LcExample_SITE_KEY"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stripe-config
  namespace: altamedica
data:
  publishable-key: "pk_live_example"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webrtc-config
  namespace: altamedica
data:
  turn-servers: |
    [
      {
        "urls": "turn:turn.altamedica.com:3478",
        "username": "altamedica",
        "credential": "turnServerPassword"
      },
      {
        "urls": "turn:turn2.altamedica.com:3478",
        "username": "altamedica",
        "credential": "turnServerPassword"
      }
    ]
  ice-servers: |
    [
      {"urls": "stun:stun.l.google.com:19302"},
      {"urls": "stun:stun1.l.google.com:19302"}
    ]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-config
  namespace: altamedica
data:
  region: "us-east-1"
  recording-bucket: "altamedica-recordings"
  assets-bucket: "altamedica-assets"
  backup-bucket: "altamedica-backups"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: altamedica
data:
  prometheus-targets: |
    - targets:
      - api-server:3001
      - doctors-app:3002
      - patients-app:3003
      - admin-app:3005
      - signaling-server:8888
  grafana-dashboards: |
    {
      "dashboards": [
        "api-metrics",
        "application-health",
        "webrtc-sessions",
        "database-performance",
        "security-events"
      ]
    }
  alert-rules: |
    groups:
    - name: altamedica_alerts
      rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High error rate detected
      - alert: PodMemoryUsage
        expr: container_memory_usage_bytes / container_spec_memory_limit_bytes > 0.9
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Pod memory usage above 90%