apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: altamedica-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/altamedica/platform
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values.yaml
        - values-production.yaml
      parameters:
        - name: global.environment
          value: production
        - name: global.domain
          value: altamedica.com
  destination:
    server: https://kubernetes.default.svc
    namespace: altamedica
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/minReplicas
        - /spec/maxReplicas
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: altamedica
  namespace: argocd
spec:
  description: AltaMedica Healthcare Platform Project
  sourceRepos:
    - 'https://github.com/altamedica/*'
    - 'https://charts.bitnami.com/bitnami'
    - 'https://helm.elastic.co'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://grafana.github.io/helm-charts'
    - 'https://kubernetes.github.io/ingress-nginx'
    - 'https://charts.jetstack.io'
  destinations:
    - namespace: 'altamedica*'
      server: https://kubernetes.default.svc
    - namespace: 'argocd'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      policies:
        - p, proj:altamedica:admin, applications, *, altamedica/*, allow
        - p, proj:altamedica:admin, repositories, *, *, allow
        - p, proj:altamedica:admin, clusters, *, *, allow
      groups:
        - altamedica:admins
    - name: developer
      policies:
        - p, proj:altamedica:developer, applications, get, altamedica/*, allow
        - p, proj:altamedica:developer, applications, sync, altamedica/*, allow
        - p, proj:altamedica:developer, applications, action/*, altamedica/*, allow
      groups:
        - altamedica:developers
    - name: readonly
      policies:
        - p, proj:altamedica:readonly, applications, get, altamedica/*, allow
      groups:
        - altamedica:readonly