#!/bin/bash

echo "🚀 Configurando Vercel Storage (PostgreSQL + KV Redis)"
echo "======================================================"
echo ""
echo "📝 Pasos manuales rápidos:"
echo ""
echo "1. Ve a: https://vercel.com/dashboard/stores"
echo ""
echo "2. Click en 'Create Database'"
echo "   - Selecciona: Postgres"
echo "   - Nombre: altamedica-db"
echo "   - Region: Elige la más cercana"
echo ""
echo "3. Click en 'Create Database' otra vez"
echo "   - Selecciona: KV (Redis)"
echo "   - Nombre: altamedica-kv"
echo "   - Region: La misma que Postgres"
echo ""
echo "4. En cada base de datos, ve a '.env.local' tab y copia las variables"
echo ""
echo "5. Pega las variables aquí abajo:"
echo ""
echo "================================"
echo "POSTGRES (ejemplo):"
echo "POSTGRES_URL="
echo "POSTGRES_PRISMA_URL="
echo "POSTGRES_URL_NON_POOLING="
echo ""
echo "KV REDIS (ejemplo):"
echo "KV_URL="
echo "KV_REST_API_URL="
echo "KV_REST_API_TOKEN="
echo "KV_REST_API_READ_ONLY_TOKEN="
echo "================================"
echo ""
echo "✅ Después ejecuta: node scripts/migrate-to-vercel.js"