apiVersion: v2
name: altamedica
description: AltaMedica Healthcare Platform - Complete Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - healthcare
  - telemedicine
  - medical
  - hipaa
home: https://altamedica.com
sources:
  - https://github.com/altamedica/platform
maintainers:
  - name: AltaMedica DevOps Team
    email: devops@altamedica.com
icon: https://altamedica.com/logo.svg

dependencies:
  - name: postgresql
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  
  - name: redis
    version: 17.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  
  - name: elasticsearch
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  
  - name: kibana
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: kibana.enabled
  
  - name: prometheus
    version: 19.3.3
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  
  - name: grafana
    version: 6.50.7
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  
  - name: ingress-nginx
    version: 4.5.2
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
  
  - name: cert-manager
    version: 1.11.0
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled

annotations:
  artifacthub.io/changes: |
    - Initial release of AltaMedica platform
    - HIPAA compliant configuration
    - Multi-tenant support
    - WebRTC signaling server
    - Complete monitoring stack
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/license: MIT
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/bitnami/postgresql
    - url: https://artifacthub.io/packages/helm/bitnami/redis