global:
  resolve_timeout: 5m

route:
  receiver: 'default'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'default'
    email_configs:
      - to: 'ops@altamedica.com'
        from: 'alertmanager@altamedica.com'
        smarthost: 'smtp.altamedica.com:587'
        auth_username: 'alertmanager@altamedica.com'
        auth_identity: 'alertmanager@altamedica.com'
        auth_password: 'REEMPLAZAR_PASSWORD'
        require_tls: true
    webhook_configs:
      - url: 'http://webhook-service:8080/alert'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service'] 