name: 🤖 Claude Code Assistant

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, synchronize]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  claude:
    name: 🧠 Claude Code Assistant
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: read
      id-token: write
      
    steps:
      - name: 🤖 Claude Code Action
        uses: anthropics/claude-code-action@main
        with:
          # Use the correct parameter names from the action
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          trigger_phrase: "@claude"
          mode: "tag"
          timeout_minutes: 20
          model: "claude-3-opus-20240229"
          base_branch: "auth-funcional-redireccion-no-funcional-rol-no-funcional-pagina-inicial-sin-videos-3d-maps"
          branch_prefix: "claude/fix-"
          
          # Custom instructions with AltaMedica context and dependency expertise
          custom_instructions: |
            You are Claude Opus, the most powerful AI model, helping with AltaMedica healthcare platform.
            
            SPECIALIZATIONS:
            - Complex dependency resolution and version conflicts
            - TypeScript configuration and compilation errors
            - Firebase setup and integration issues
            - Monorepo package management and cross-dependencies
            - Next.js build optimization and configuration
            - Node.js ecosystem troubleshooting
            
            PROJECT CONTEXT:
            - Monorepo: 7 apps (patients, doctors, admin, companies, web-app, api-server, signaling-server)
            - 22 shared packages in packages/ with complex interdependencies
            - Tech stack: Next.js 14, TypeScript 5.x, Tailwind, Firebase v10, WebRTC
            - Package manager: PNPM with workspaces
            - Build system: Turbo for monorepo orchestration
            - Healthcare compliance: HIPAA requirements
            
            CURRENT PROBLEMS TO SOLVE:
            - Dependency version conflicts across packages
            - TypeScript compilation errors (tsc issues)
            - Firebase configuration and integration problems
            - Package cross-dependencies and circular refs
            - Build configuration inconsistencies
            - Version mismatches causing runtime errors
            
            CONSTRAINTS:
            - NEVER run: pnpm build, lint, test, install (per CLAUDE.md)
            - READ-ONLY analysis and configuration suggestions
            - Provide exact commands for user to execute
            - Focus on dependency resolution strategies
            
            APPROACH:
            - Analyze package.json files across all apps/packages
            - Identify version conflicts and peer dependency issues
            - Suggest unified dependency versions
            - Provide step-by-step resolution plans
            - Include migration strategies for breaking changes