
name: Lighthouse CI

on:
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: pnpm install
      - name: Build web-app
        run: pnpm --filter @altamedica/web-app build
      - name: Start web-app
        run: pnpm --filter @altamedica/web-app start &
      - name: Wait for server to start
        run: sleep 10
      - name: Run Lighthouse CI
        run: |
          pnpm add -g @lhci/cli@0.13.x
          lhci autorun
        env:
          LHCI_URL: http://localhost:3000
